---
abstract: 'Substitutions for files in dzil'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Path::Class: 0
  Test::DZil: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  Module::Build::Tiny: 0.021
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Substitute
requires:
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Substitute
  repository: git://github.com/Leont/dist-zilla-plugin-substitute.git
version: 0.001
